version: '3.8'

services:
  web:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    command: >
      sh -c "
      npm install &&
      npm start"
    environment:
      - NODE_ENV=development
